path
demianruban/demianruban.github.io pull request #11
Opened 2022-04-12 17:37 UTC by Tigee03

2022-04-12 19:11 UTC, demianruban commented on style.css
> -.card-dark-style{
this style is in use by Nikita's code ([contacts.html](https://github.com/demianruban/openvision-frontend/blob/main/contacts.html))

2022-04-12 19:12 UTC, demianruban commented on style.css
> -.imagine-style{
this style is also in use by Nikita's code ([contacts.html](https://github.com/demianruban/openvision-frontend/blob/main/contacts.html))

2022-04-12 19:13 UTC, demianruban requested changes
We use indentation with 4 spaces. Please edit that in style.css

2022-04-13 05:07 UTC, Tigee03 commented
Code formatted

2022-04-13 07:33 UTC, merged